#
#server:
#  port: 3306
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/Exam_portal?serverTimezone=UTC
#    username: root
#    password: EMMARESCUE
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect


spring:
  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: https://www.googleapis.com
        clientId: "1006167054424-vgf13e2d85q918umpdku10un40613m1v.apps.googleusercontent.com"
        clientSecret: "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"