
server:
  port: 3306

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Exam_portal?serverTimezone=UTC
    username: root
    password: EMMARESCUE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect