#
#server:
#  port: 3306

spring:
  datasource:
    url: jdbc:mysql://examsdb.cp26gui2amit.eu-north-1.rds.amazonaws.com:3306/examinationDB
    username: root
    password: EMMARESCUe12
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


#spring:
#  security:
#    oauth2:
#      resourceserver:
#        opaque-token:
#          introspection-uri: https://www.googleapis.com
#        clientId: "1006167054424-vgf13e2d85q918umpdku10un40613m1v.apps.googleusercontent.com"
#        clientSecret: "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"