
server:
  port: 5432

spring:
  datasource:
    url: postgres://exams_lwae_user:8uwwWUekA7zIzMIl5WBc8Ph2RBtnBM4j@dpg-cj9v0tue546c73ebdr80-a.oregon-postgres.render.com/exams_lwae
    username: exams_lwae_user
    password: 8uwwWUekA7zIzMIl5WBc8Ph2RBtnBM4j
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresSQLDialect